spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=evenza_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=manirenkan
spring.datasource.password=200524
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true