spring.datasource.url=jdbc:sqlserver://DESKTOP-HLRMVB4:1433;databaseName=evenza;encrypt=true;trustServerCertificate=true;sendTimeAsDatetime=false
spring.datasource.username=sa
spring.datasource.password=200507301184
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true